require('dotenv').config();
const scannerRoutes = require('./scanner');
const express = require('express');
const cors = require('cors');
const compression = require('compression');
const morgan = require('morgan');
const rateLimit = require('express-rate-limit');
const cron = require('node-cron');
const db = require('./db');
const authRoutes = require('./routes/auth');
const companyRoutes = require('./routes/companies');
const customerRoutes = require('./routes/customers');
const submissionRoutes = require('./routes/submissions');
const cardRoutes = require('./routes/cards');
const psaRoutes = require('./routes/psa');
const portalRoutes = require('./routes/portal');
const { refreshAllSubmissions } = require('./services/psaService');
const app = express();
const PORT = process.env.PORT || 3000;
app.use(cors({ origin: true, credentials: true }));
app.use('/api/scanner', scannerRoutes);
app.use(compression());
app.use(morgan('combined'));
app.use(express.json({ limit: '10mb' }));
app.use('/api/', rateLimit({ windowMs: 15 * 60 * 1000, max: 100, message: { error: 'Too many requests' } }));
app.get('/health', (req, res) => { res.json({ status: 'ok', app: 'SlabDash', timestamp: new Date().toISOString() }); });
app.use('/api/auth', authRoutes);
app.use('/api/companies', companyRoutes);
app.use('/api/customers', customerRoutes);
app.use('/api/submissions', submissionRoutes);
app.use('/api/cards', cardRoutes);
app.use('/api/psa', psaRoutes);
app.use('/api/portal', portalRoutes);
app.use((req, res) => { res.status(404).json({ error: 'Endpoint not found' }); });
app.use((err, req, res, next) => { console.error('Error:', err); res.status(500).json({ error: 'Internal server error' }); });
cron.schedule('0 */6 * * *', async () => { try { await refreshAllSubmissions(); } catch (error) { console.error('Refresh failed:', error); } });
const startServer = async () => { try { await db.query('SELECT NOW()'); console.log('Database connected'); app.listen(PORT, () => { console.log('SlabDash API running on port ' + PORT); }); } catch (error) { console.error('Failed to start:', error); process.exit(1); } };
startServer();
module.exports = app;
